# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True, verbose_name='Url path')),
                ('header', models.CharField(max_length=64, verbose_name='Header')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
