# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True, verbose_name='Url path')),
                ('header', models.CharField(max_length=64, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
                ('edit_time', models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 24, 20, 5, 27, 951879), verbose_name='Article edit time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleGroup',
        ),
    ]
