# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='article_slug', unique=True, verbose_name='Url path')),
                ('header', models.CharField(default='Article header', max_length=64, verbose_name='Header')),
                ('description', models.TextField(default='Article description', verbose_name='Content')),
                ('content', redactor.fields.RedactorField(default='Article content', verbose_name='Content')),
                ('edit_time', models.DateTimeField(verbose_name='Article edit time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('next_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_next', to='article.Article', verbose_name='Next article')),
                ('prev_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_prev', to='article.Article', verbose_name='Previous article')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleGroup',
        ),
    ]
