# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160224_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prev_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Next article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='edit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 27, 18, 42, 9, 764287), verbose_name='Article edit time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url path'),
        ),
    ]
