# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160227_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='next_article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_next', to='article.Article', verbose_name='Next article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='edit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 27, 19, 11, 49, 112787), verbose_name='Article edit time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prev_article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_prev', to='article.Article', verbose_name='Previous article'),
        ),
    ]
