# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160227_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 27, 19, 19, 20, 440413), verbose_name='Article edit time'),
        ),
    ]
