# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20160227_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='next_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prev_article',
        ),
        migrations.AlterField(
            model_name='article',
            name='edit_time',
            field=models.DateTimeField(verbose_name='Article edit time'),
        ),
    ]
