# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20160227_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Article description', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='Article conten', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(default='Article header', max_length=64, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='Article slug', unique=True, verbose_name='Url path'),
        ),
    ]
