# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:37
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20160227_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_markdown.models.MarkdownField(default='Article conten', verbose_name='Content'),
        ),
    ]
