# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20160227_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=redactor.fields.RedactorField(default='Article content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='article_slug', unique=True, verbose_name='Url path'),
        ),
    ]
