# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20160227_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='K. Kulikov home page', max_length=128, verbose_name='Page title')),
                ('keywords', models.CharField(max_length=256, verbose_name='Keywords for search engines')),
                ('description', models.CharField(max_length=256, verbose_name='Description of a web page')),
                ('author', models.CharField(max_length=64, verbose_name='Author of a web page')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='common_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.CommonData', verbose_name='Meta data and header'),
            preserve_default=False,
        ),
    ]
