# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_commondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='common_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.CommonData', verbose_name='Meta data and header'),
        ),
    ]
