# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_article_common_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='Article content', verbose_name='Content'),
        ),
    ]
