# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:18
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20160302_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Article content', verbose_name='Content'),
        ),
    ]
